language: minimal
services: docker
env:
- TAG=${TRAVIS_BUILD_ID}
before_install:
- docker -v && docker-compose -v
- source ./scripts/build-deploy-functions.sh
- download_and_install_kubectl
- generate_ssh_pk
install:
- build_and_push_docker_images
- login_ssh_prod_host
# Executed on prod host
- cd ./udacity-cloud-developer-c3-project
- git pull
- source ./scripts/build-deploy-functions.sh
- k8s_deploy