apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
    version: $TAG
  name: reverseproxy-$TAG
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: $DOCKER_USERNAME/reverseproxy:$TAG
        name: reverseproxy
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
